version: '3.4'
services:
  ibgateway:
    image: dvasdekis/ib-gateway-docker:v978
    container_name: ibgateway
    network_mode: "host"
    environment:
      - TWSUSERID
      - TWSPASSWORD
      - TRADING_MODE
      - XVFB_ARGS="-ac -screen 0 1024x768x16 +extension RANDR"
    restart: always
        #    command: tail -f /dev/null

  trader:
    build: .
    depends_on:
      - ibgateway
    image: goilya/trader:v1
    container_name: trader
    network_mode: "host"
    restart: on-failure
    volumes:
      - /mnt/hal_hdf5:/hdf
    command: ["./wait-for-it.sh", "127.0.0.1:4003", "--", "python", "./trader.py", "--host", "127.0.0.1", "--port","4003", "--store", "/hdf/bond_data.h5", "--model", "/hdf/bond_model_210225.joblib", "--log", "/hdf/hal.log"]

